services:
  redis:
    image: redis:7-alpine
    container_name: pos-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    container_name: pos-mongo
    ports:
      - "27017:27017"
    restart: unless-stopped